#!/bin/bash

# This script just makes a binary grep for \AA and \JS on PNG files

workdir=$1

echo "Items matching \JS code:"
grep -al '/\JS' $workdir/*.png
echo ""

echo "Items matching \AA code:"
grep -al '/\AA' $workdir/*.png
echo ""
